###
//댓글 등록 
POST http://localhost:5000/api/posts/2/comments
Content-Type: application/json


{
    "nickname": "string",
    "content": "This is a comment",
    "password": "12345"
}


###
//댓글 목록조회 
GET http://localhost:5000/api/posts/2/comments


###
//댓글 수정 

PUT http://localhost:5000/api/comments/2
Content-Type: application/json

{
    "nickname": "UpdatedNickname",
    "content": "Updated content.",
    "password": "12345"
}


###
//댓글 삭제 

DELETE http://localhost:5000/api/comments/2
Content-Type: application/json

{
    "password": "12345"
}