//그룹 등록 
POST http://localhost:3000/api/groups
Content-Type: application/json

{
    "name": "Sample Group",
    "password": "securepassword",
    "imageUrl": "http://example.com/image.jpg",
    "isPublic": true,
    "introduction": "This is a sample group."
}

###
//그룹 목록 조회
GET http://localhost:3000/api/groups



###
//그룹 수정 

PUT http://localhost:3000/api/groups/1
Content-Type: application/json

{
    "name": "Updated Group Name",
    "password": "expectedPassword",
    "imageUrl": "http://example.com/newimage.jpg",
    "isPublic": true,
    "introduction": "Updated introduction."
}

